### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by ghostdevv** [Serendipity-Theme/vs-code#17]
Can you please publish serendipity & serendipity old on [open vsx](https://open-vsx.org/) so I can use this on gitpod

**Comment by michael-andreuzza** [comment]
Hey, let us have a look andI will ping you back when is up!

**Comment by michael-andreuzza** [comment]
> Can you please publish serendipity & serendipity old on [open vsx](https://open-vsx.org/) so I can use this on gitpod

Now is up! 

Just follow this link and it will appear.
https://open-vsx.org/?search=serendipity&category=&sortBy=relevance&sortOrder=desc

Thank you for the tip!
/Mike

**Comment by ghostdevv** [comment]
Amazing thank you!

**Comment by michael-andreuzza** [comment]
@ghostdevv Welcome!
