### ISSUE TITLE
Hard to see where the dividers/separators are located

### ISSUE THREAD

**Issue by fredrikaverpil** [Serendipity-Theme/vs-code#20]
Hi, and thanks for a super nice theme!

I'm having great difficulties identifying where horizontal/vertical divider/separators are located. I struggle to find the exact location with the mouse and it becomes frustrating.

You can see in this screenshot, for example, that the vertical draggable divider is somewhere left of the line numbers. But where, exactly?

![image](https://user-images.githubusercontent.com/994357/153572138-b0d273a1-e287-49c8-ab63-a0eb0a2994f3.png)

When I bring up the terminal, it gets easier to see exactly where this is, as the invisible divider line is exactly at the left end of the terminal:

![image](https://user-images.githubusercontent.com/994357/153572228-cb444185-23b4-45c1-b2f1-beb6da8eb558.png)

Some ideas of what I could potentially do about this:
- Figure out the styling syntax to override the color of the divider, so it become visible
- Figure out the styling syntax to override the background color of the explorer/side bars, and make them slightly darker than the code area background

I'm leaning towards the latter, and I just added some custom styling to my `settings.json` for this:

```json
  "workbench.colorCustomizations": {
    "[Serendipity Midnight]": {
      "sideBar.background": "#121421"
    }
  }
```

![image](https://user-images.githubusercontent.com/994357/153573767-c3fbc25c-07c2-42b3-ba29-082a57cce5c3.png)

Maybe you'd like to consider building something like this straight into the theme?

**Comment by michael-andreuzza** [comment]
Hey, thank you Fredrik!

That's part of the minimal design, is meant to be like this. 

I won't build it on the theme, because is what I wanted to achieve. If you want to, you have the old version here:
- 
https://marketplace.visualstudio.com/items?itemName=wicked-labs.old-serendipity
