### ISSUE TITLE
File compares / diffs very hard to read

### ISSUE THREAD

**Issue by fredrikaverpil** [Serendipity-Theme/vs-code#21]
Hi again! 👋 

When I'm comparing files or performing diffs in vscode with the serendipity midnight theme, I get a border around each line which was changed (and even borders around individual parts of a line). This makes comparisons/diffs incredibly noisy and hard to read - and is everything but minimal 😉 . I can provide a screenshot for you if you like (currently working on proprietary code while writing this).

You can compare with a regular diff in GitHub which only has a red/green background color (no border around each and every changed line) which looks a lot cleaner (but using a less compelling theme).

I think an improvement would be to leave the background color as-is for the code that changed, but remove the borders. What do you think?

**Comment by Chaphasilor** [comment]
Hi @fredrikaverpil, this is actually a problem that we're already aware of. We'll keep you posted about any updates! 😁

**Comment by fredrikaverpil** [comment]
Great to hear you're already aware of it 💪  and it already looks much, much better in #22 😃

**Comment by Chaphasilor** [comment]
There you go, hope that helps! 😁
