### ISSUE TITLE
Jetbrains IDE's support

### ISSUE THREAD

**Issue by jonorozcoc** [Serendipity-Theme/vs-code#23]
First, thanks for this excellent theme!

I want to know if you have in mind supporting Jetbrains IDE's aka. IntelliJ, RubyMine, etc

**Comment by michael-andreuzza** [comment]
Hola Jonatan, muchísimas gracias. 

Pues o intente con la version anterior y solo se puede cambiar el texto.

Si encuentro a alguien que sepa hacerlo mejor, si.

**Comment by michael-andreuzza** [comment]
I will close this issue because i have no plans for Jetbrains.
