### ISSUE TITLE
Syntax highlighting is broken in Polyglot Notebooks

### ISSUE THREAD

**Issue by dodbrian** [Serendipity-Theme/vs-code#25]
When the theme is active the syntax highlighting stops working in polyglot notebooks. 

Before activating:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/2762450/227005867-756d4234-f3fb-41fc-8621-5c41124e8d96.png">

and after:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/2762450/227005981-52268682-1c25-44a8-aad9-4eb8c25de443.png">

**Comment by dodbrian** [comment]
Here's the link to description of Polyglot Notebooks: https://code.visualstudio.com/docs/languages/polyglot

**Comment by michael-andreuzza** [comment]
> Here's the link to description of Polyglot Notebooks: https://code.visualstudio.com/docs/languages/polyglot

I have to see how to fix that. I wonder why...

Thank you!
