### ISSUE TITLE
Source control: hidden input box validation

### ISSUE THREAD

**Issue by lmarello** [Serendipity-Theme/vs-code#26]
Hi there 👋🏼

I found a problem within the "Source Control" tab that does not allow the "input box validation" to be seen (because it has 0% opacity)

![image](https://github.com/Serendipity-Theme/vs-code/assets/46272210/f9885c6b-a13d-4c6a-ab3e-4ab413667c3b)

This is due to the color used in the `inputValidation.warningBackground` property, for example, changing this to another one  you can see it correctly

![image](https://github.com/Serendipity-Theme/vs-code/assets/46272210/cfc76f98-a9b8-431f-984a-ce598ad9b709)

The same thing happens with properties `inputValidation.infoBackground` and `inputValidation.errorBackground`, and probably others, because #0000 takes 0% opacity.

If you wish, I can create a PR with the colors you think are appropriate.

**Comment by michael-andreuzza** [comment]
Hey Leo, disculpame, no he visto el issue. 
Si, si quieres arreglarlo adelante, por mi sin problemas.

**Comment by lmarello** [comment]
> Hey Leo, disculpame, no he visto el issue. Si, si quieres arreglarlo adelante, por mi sin problemas.

Hola! No será posible, ya que removieron dicha opcion. 
Hay un [issue](https://github.com/microsoft/vscode/issues/200419) sobre este input debido a que no fue reportado en las _releases notes._

Por el momento tenemos lo siguiente:
![image](https://github.com/Serendipity-Theme/vs-code/assets/46272210/2b55fc68-c8d5-40ee-9e83-d6e1abab4da5)

Al hacer hover:
![image](https://github.com/Serendipity-Theme/vs-code/assets/46272210/b1be55cf-749d-40f1-98ad-2738ae556839)

Para ello se debe habilitar
```json
 "git.inputValidation": true,
 "git.inputValidationSubjectLength": 50
```

**Comment by michael-andreuzza** [comment]
Bueno, se intento :-), supongo que se dejamos tal y como esta mejor no?

**Comment by lmarello** [comment]
> Bueno, se intento :-), supongo que se dejamos tal y como esta mejor no?

Totalmente de acuerdo! 👍

**Comment by michael-andreuzza** [comment]
Muchísimas gracias por la atención y de nuevo disculpa la tardanza.
